name: SYNC
on:
  pull_request:
    types:
      - synchronize

jobs:
  runs-on: ubuntu-18.04
  steps:
    - name: echo_new_commit
      run: |
        echo "github.event.number : ${github.event.number} "
        echo "github.event_name : ${github.event_name} "
        echo "github.event : ${github.event.label} "
        echo "!!! new commit has been pushed to !!!"
 
