name: LABELED
on:
  pull_request:
    types:
      - labeled

jobs:
  labeled:
    runs-on: ubuntu-18.04
    steps:
      - name: echo_labeled
        run: |
          echo "label created event is triggered"
          labels=${{join(github.event.pull_request.labels)}}
          echo "labels are $labels"
